In [1]:
import pandas as pd
import numpy as np

import warnings
warnings.filterwarnings('ignore')

check file is manually filled in, from the report and the TMT files, linking the tube code (e.g. M_H_20) to the corresponding label (amyloid-Beta Status), AIBL.Id, Collection

In [2]:
check_protemics = pd.read_excel('../data/raw_data/check.xlsx', sheet_name='proteomics')
print("Column included: ", check_protemics.columns)
print("Dimension: ", check_protemics.shape)

check_metabolomics = pd.read_excel('../data/raw_data/check.xlsx', sheet_name='metabolomics')
print("Column included: ", check_metabolomics.columns)
print("Dimension: ", check_metabolomics.shape)

Column included:  Index(['label_name', 'Gender', 'label', 'AIBL.ID', 'Collection'], dtype='object')
Dimension:  (90, 5)
Column included:  Index(['label_name', 'Gender', 'label', 'AIBL.ID', 'Collection',
       'Tube Barcode'],
      dtype='object')
Dimension:  (90, 6)

In [3]:
omics_type_df = pd.DataFrame()

#### For Proteomics

In [4]:
# proteomics_df = pd.read_csv('../data/preprocessing/proteomics/Proteomics_impute_removecontam_IRS_VSN.csv',index_col=0)
# print(proteomics_df.shape)
# ## use the protein without imputations
# proteomics_df = proteomics_df[proteomics_df['imputed'] == False]
# proteomics_df = proteomics_df.transpose()
# proteomics_df = proteomics_df.drop(index=['Contaminant', 'ID', 'imputed'])
# proteomics_df.reset_index(inplace=True)
# proteomics_df.rename(columns={'index': 'label_name'}, inplace=True)

# proteomics_merge_df = pd.merge(proteomics_df, check_protemics, on = 'label_name', how = 'left')
# proteomics_merge_df = proteomics_merge_df.drop(['label_name', 'Gender'], axis=1)
# proteomics_merge_df = proteomics_merge_df.apply(lambda col: pd.to_numeric(col, errors='coerce') if col.name != 'label' else col)
# print(proteomics_merge_df.shape)
# proteomics_merge_df

In [3]:
# ############## COMBAT original
# proteomics_df = pd.read_csv('../data/preprocessing/proteomics/results_SL_IRS_COMBAT_VSN_multi_fullresults_mapedforSabrina.csv',index_col=0)
# print(proteomics_df.shape)
# proteomics_df = proteomics_df.transpose()
# proteomics_df.reset_index(inplace=True)
# proteomics_df.rename(columns={'index': 'AIBL.ID'}, inplace=True)
# proteomics_df.head(2)
# proteomics_df = proteomics_df.apply(lambda col: pd.to_numeric(col, errors='coerce') if col.name != 'label' else col)

(558, 90)

In [4]:
###### no sex covariant
proteomics_df = pd.read_csv('../data/preprocessing/proteomics/ORCA_IRS_COMBAT_nosexcovar_021024_Yihan.csv',index_col=0)
print(proteomics_df.shape)
## use the protein without imputations
proteomics_df = proteomics_df.transpose()
proteomics_df.reset_index(inplace=True)
proteomics_df.rename(columns={'index': 'AIBL.ID'}, inplace=True)
proteomics_df = proteomics_df.apply(lambda col: pd.to_numeric(col, errors='coerce') if col.name != 'label' else col)

(596, 90)

In [5]:
proteomics_df

name,AIBL.ID,A1BG,A2M,ABI3BP,ACE,ACTB,ACTC1,ACTN1,ADA2,ADAMDEC1,...,TUBA1B,TXN,VASN,VCAM1,VCL,VNN1,VSIG4,VTN,VWF,YWHAZ
0,1705,11.657373,13.251508,5.926799,7.036672,10.225859,6.071756,5.177238,6.831299,4.921385,...,6.000555,5.461619,8.858089,9.903681,6.196691,6.965438,4.254527,11.746896,11.914403,7.287674
1,528,11.663114,13.441099,5.952221,6.817977,9.214318,5.151370,4.217886,6.697860,5.427281,...,5.056175,5.026669,8.608982,9.923734,6.787682,7.645371,4.524581,11.449852,10.455757,6.439370
2,2026,12.109471,13.479028,5.410489,6.860000,9.538766,5.609914,4.496821,6.651321,5.002545,...,5.543012,5.142294,8.444375,9.356390,6.350361,7.618675,4.672535,11.721370,10.967974,6.611821
3,644,11.694874,13.634315,5.724415,6.963037,10.016987,5.832177,4.701549,7.405052,5.398298,...,5.371026,5.180673,8.473177,10.073121,6.165202,8.759130,4.818125,11.657220,10.593997,7.007654
4,1548,11.899473,13.076753,5.511962,6.914931,9.761795,5.959668,4.274470,7.153120,5.625269,...,4.947970,4.991450,8.529247,9.812404,6.861373,8.190119,5.203991,11.751883,10.687003,6.472772
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
85,1500,11.873664,13.426203,5.766286,7.080213,9.911757,5.772246,4.762125,7.151826,5.338015,...,5.260301,5.267187,8.585386,10.079468,7.074000,7.605266,4.426045,11.451488,11.250351,6.943994
86,711,11.581490,13.225667,5.721412,6.679640,9.715072,5.576742,4.852865,6.834408,5.645950,...,5.238938,5.116488,8.391798,9.977508,6.430203,7.403074,4.170039,11.521441,11.626999,7.015515
87,985,12.026218,14.034479,5.988934,6.412149,9.701236,5.770454,4.650562,6.744437,5.520821,...,5.204459,5.166169,8.466861,9.870911,6.470583,8.155850,4.735602,11.944247,10.592007,7.044792
88,1456,12.003099,13.675777,6.211073,6.665981,9.701395,5.448954,4.425937,7.188012,4.810395,...,4.657088,5.038862,8.369068,9.984635,6.543719,8.259908,5.003383,11.925000,11.367311,6.922924
89,27,11.799363,13.202624,5.684453,6.967475,9.756910,5.524023,4.730842,6.876667,5.591876,...,5.257523,5.003542,8.710082,9.553372,7.007774,8.004508,5.379048,11.371527,11.150260,6.852297

In [6]:
proteomics_cols = proteomics_df.columns.to_list()
proteomics_cols = [value for value in proteomics_cols if value not in ['AIBL.ID']]
print(proteomics_df.select_dtypes(include=['object', 'category']).columns)

Index([], dtype='object', name='name')

In [7]:
proteomics_df = pd.merge(proteomics_df, check_protemics[['Gender','label','AIBL.ID']], on = 'AIBL.ID', how = 'left')
proteomics_df

,AIBL.ID,A1BG,A2M,ABI3BP,ACE,ACTB,ACTC1,ACTN1,ADA2,ADAMDEC1,...,VASN,VCAM1,VCL,VNN1,VSIG4,VTN,VWF,YWHAZ,Gender,label
0,1705,11.657373,13.251508,5.926799,7.036672,10.225859,6.071756,5.177238,6.831299,4.921385,...,8.858089,9.903681,6.196691,6.965438,4.254527,11.746896,11.914403,7.287674,M,N
1,528,11.663114,13.441099,5.952221,6.817977,9.214318,5.151370,4.217886,6.697860,5.427281,...,8.608982,9.923734,6.787682,7.645371,4.524581,11.449852,10.455757,6.439370,M,H
2,2026,12.109471,13.479028,5.410489,6.860000,9.538766,5.609914,4.496821,6.651321,5.002545,...,8.444375,9.356390,6.350361,7.618675,4.672535,11.721370,10.967974,6.611821,F,N
3,644,11.694874,13.634315,5.724415,6.963037,10.016987,5.832177,4.701549,7.405052,5.398298,...,8.473177,10.073121,6.165202,8.759130,4.818125,11.657220,10.593997,7.007654,F,N
4,1548,11.899473,13.076753,5.511962,6.914931,9.761795,5.959668,4.274470,7.153120,5.625269,...,8.529247,9.812404,6.861373,8.190119,5.203991,11.751883,10.687003,6.472772,M,N
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
85,1500,11.873664,13.426203,5.766286,7.080213,9.911757,5.772246,4.762125,7.151826,5.338015,...,8.585386,10.079468,7.074000,7.605266,4.426045,11.451488,11.250351,6.943994,F,N
86,711,11.581490,13.225667,5.721412,6.679640,9.715072,5.576742,4.852865,6.834408,5.645950,...,8.391798,9.977508,6.430203,7.403074,4.170039,11.521441,11.626999,7.015515,F,N
87,985,12.026218,14.034479,5.988934,6.412149,9.701236,5.770454,4.650562,6.744437,5.520821,...,8.466861,9.870911,6.470583,8.155850,4.735602,11.944247,10.592007,7.044792,F,N
88,1456,12.003099,13.675777,6.211073,6.665981,9.701395,5.448954,4.425937,7.188012,4.810395,...,8.369068,9.984635,6.543719,8.259908,5.003383,11.925000,11.367311,6.922924,F,H
89,27,11.799363,13.202624,5.684453,6.967475,9.756910,5.524023,4.730842,6.876667,5.591876,...,8.710082,9.553372,7.007774,8.004508,5.379048,11.371527,11.150260,6.852297,M,N

In [7]:
proteomics_df.to_csv('../data/merged_data/proteomics_with_label.csv')

#### For Metabolomics

In [8]:
metabolomics = pd.read_csv('../data/preprocessing/metabolomics/Metabolomics_impute_Normaliseddata_noWave.csv',index_col=0)
metabolomics.reset_index(inplace=True)
metabolomics.rename(columns={'index': 'Tube Barcode'}, inplace=True)
metabolomics['Tube Barcode'] = metabolomics['Tube Barcode'].str.split('_').str[1]
metabolomics_merge_df = pd.merge(metabolomics, check_metabolomics, on = 'Tube Barcode', how = 'right')
metabolomics_merge_df = metabolomics_merge_df.drop(['Tube Barcode', 'Class', 'label_name','Collection'], axis=1)
metabolomics_merge_df

,Acetone cyanohydrin,Acetone cyanohydrin.1,Diacetyl,2-Butyne-1_4-diol,2-Butyne-1_4-diol.1,2-Aminoacrylic acid,Malonic semialdehyde,Pyruvic acid,Butyric acid,Butyric acid.1,...,PS(O-38:2),Galabiosylceramide (d18:1/16:0),TG(12:0/18:2/21:0)[iso6],PS(O-40:4),PI(16:0/22:6),TG(12:0/20:0/22:4)[iso6],Disialosylgalactosylgloboside,Gender,label,AIBL.ID
0,-0.461142,-0.172676,0.010073,-0.099465,0.083470,0.652043,-0.210717,-0.162703,0.246997,-0.177819,...,0.199141,-0.120544,0.381379,-0.433480,-0.134549,0.004258,0.104134,F,H,837
1,-0.270671,-0.276940,-0.261819,-0.032098,-0.098075,0.276904,-0.481847,-0.113594,0.390746,-0.217511,...,0.332612,-0.069186,0.083207,0.191706,0.483267,0.462963,-0.147646,F,H,2276
2,0.256128,-0.239005,0.048329,0.137639,-0.086301,-0.638650,0.286983,0.075876,0.231817,0.251518,...,0.023560,-0.070144,-0.402250,-0.063112,0.562359,-0.998622,-0.242395,F,H,2274
3,0.093526,0.448415,0.000368,-0.115477,-0.288924,-0.747549,-0.010582,0.428010,-0.424175,0.530050,...,0.011821,-0.131660,-0.465007,0.232108,-0.220484,-0.286617,-0.286048,F,H,2321
4,-0.019898,-0.200684,0.663822,-0.468762,-0.193421,0.084386,-0.097456,-0.389847,0.891462,0.318160,...,-0.192660,0.323687,0.035683,-0.238026,-0.067759,-0.043083,1.112984,F,H,2326
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
85,0.523049,0.027965,0.121575,-0.068759,-0.322383,0.444830,0.064232,0.278173,-0.318918,-0.273604,...,-0.426061,0.099638,-1.189784,0.415346,-0.481590,-0.144937,0.440515,M,N,859
86,-0.197090,0.022827,-0.018414,0.057698,-0.227599,-0.732066,0.837810,0.425034,0.111957,0.172558,...,0.432924,0.160727,0.398778,-0.400296,0.220537,0.621427,-0.299912,M,N,2332
87,-0.510271,-0.239946,0.294435,-0.374088,-0.227367,-0.270230,0.190954,0.160205,0.180459,-0.144032,...,0.003264,0.175733,0.439063,0.105710,-0.328889,0.390637,-0.679474,M,N,1514
88,-0.241158,-0.238286,0.144317,-0.210737,-0.123480,-1.056651,0.026226,0.228530,0.230646,-0.047158,...,-0.276280,-0.333804,0.408630,-0.058287,-0.347299,-0.030750,-0.485750,M,N,2077
89,-0.098947,-0.198493,-0.234956,0.209711,0.078874,0.636094,-0.454486,-0.620165,-0.078459,0.087848,...,-0.347802,-0.251899,0.273623,-0.179296,-0.731438,0.236029,-0.188308,M,N,140

In [9]:
metabolomics_cols = metabolomics_merge_df.columns.to_list()
metabolomics_cols = [value for value in metabolomics_cols if value not in ['AIBL.ID', 'Gender','label']]

In [10]:
metabolomics_merge_df.to_csv('../data/merged_data/metabolomics_with_label.csv')

#### Merge omics

In [10]:
# merge_df = pd.merge(metabolomics_merge_df,proteomics_merge_df,how = 'inner',on=['AIBL.ID', 'Collection','label'])
merge_df = pd.merge(metabolomics_merge_df,proteomics_df,how = 'inner',on=['AIBL.ID', 'Gender','label'])
print(merge_df.shape)
print(merge_df.select_dtypes(include=['object', 'category']).columns)

(90, 1944)
Index(['Gender', 'label'], dtype='object')

['FA hydroxy(7:0)', 'FA methyl(8:0)', 'FA oxo(9:0) oxo-nonanoic acid', 'FA hydroxy(9:0) hydroxy-nonanoic acid', 'FA (10:2) Decadienoic acid', 'FA methyl(7:0)', 'FA methyl(12:0) dodecanoic acid', 'FA hydroxy(12:0) dodecanoic acid', 'FA (14:1)nonanoic acid', 'FA (13:2) tridecadienoic acid', 'FA hydroxy(13:0) tridecanoic acid', 'FA oxo(14:1) cyclopentanebutanoic acid', 'FA oxo(14:2) cyclopentanebutanoic acid', 'FA methyl(14:0)', 'FA methyl(14:0) dodecanedioic acid', 'FA (16:3)', 'FA methyl(15:0) tridecanedioic acid', 'FA methyl(16:0)] tetradecanedioic acid', 'FA (18:4)', 'FA (18:3)', 'FA (18:2)', 'FA hydroxy(18:1)', 'FA (19:1)', 'FA hydroxy(18:0)', 'FA hydroxy(26:0)', 'FAHFA(16:0/9-O-18:0)', 'FABP4', 'FAM20C', 'FAP', 'HGFAC', 'IGFALS']

#### Merge with AIBL

In [15]:
AIBL_raw = pd.read_excel('../data/raw_data/AIBL_2023.xlsx')
AIBL_raw['Demographic.YearMonthOfBirth']=AIBL_raw['Demographic.YearMonthOfBirth'].astype(str) + '01'
AIBL_raw['Demographic.YearMonthOfBirth'] = pd.to_datetime(AIBL_raw['Demographic.YearMonthOfBirth'], format='%Y%m%d')
AIBL_raw['Progress Summary.Date of NP assessment'] = pd.to_datetime(AIBL_raw['Progress Summary.Date of NP assessment'], format='%d/%m/%Y')
AIBL_raw['Age'] = (AIBL_raw['Progress Summary.Date of NP assessment'] - AIBL_raw['Demographic.YearMonthOfBirth']).dt.days // 365

In [16]:
AIBL_raw[AIBL_raw['Neuropsych.Simple Classification'] == 'AD']['AIBL ID'].nunique()

678

In [17]:
AIBL_raw['AIBL ID'].nunique()

3438

In [18]:
AIBL_need = AIBL_raw.copy()
AIBL_need = AIBL_need.rename(columns = {'AIBL ID':'AIBL.ID'})

merge_df = pd.merge(merge_df, check_protemics[['AIBL.ID', 'Collection']], on = ['AIBL.ID'])
omics_merge_aibl_df = pd.merge(merge_df,AIBL_need,how = 'left',on = ['AIBL.ID', 'Collection'])
display(omics_merge_aibl_df.head(2))
print("Dimension: ", omics_merge_aibl_df.shape)

,Acetone cyanohydrin,Acetone cyanohydrin.1,Diacetyl,2-Butyne-1_4-diol,2-Butyne-1_4-diol.1,2-Aminoacrylic acid,Malonic semialdehyde,Pyruvic acid,Butyric acid,Butyric acid.1,...,ShortIq.MakingDecisions,ShortIq.HandlingMoney,ShortIq.HandingFinancial,ShortIq.HandlingEveryday,ShortIq.UsingIntelligence,ShortIq.TotalScore,FollowUp.HighCholesterolDiagnosis,FollowUp.HypertensionDiagnosis,FollowUp.DiabetesDiagnosis,Age
0,-0.461142,-0.172676,0.010073,-0.099465,0.083470,0.652043,-0.210717,-0.162703,0.246997,-0.177819,...,Not much change,NaN,Not much change,Not much change,Not much change,3.00,2010.0,NaN,NaN,69.0
1,-0.270671,-0.276940,-0.261819,-0.032098,-0.098075,0.276904,-0.481847,-0.113594,0.390746,-0.217511,...,Not much change,Not much change,Not much change,Not much change,Not much change,3.13,NaN,NaN,NaN,67.0

Dimension:  (90, 3344)

In [16]:
omics_merge_aibl_df.to_csv('../data/merged_data/omics_merge_aibl.csv')

omics with demographic information

In [19]:
print(merge_df.shape)

aibl_demo_df = omics_merge_aibl_df[['AIBL.ID', 'Collection', 'Demographic.ApoE genotype','Demographic.Years of Education','Demographic.Years of Education Exact', 'Age', 'Demographic.Sex',
                                    'Demographic.Primary Occupation', 'Demographic.Retirement Status','Demographic.Current Marital Status', 'Demographic.Country of Birth', 'Demographic.Handedness', 'Vital Signs.Body Mass Index', 'Demographic.GDS']]
aibl_demo_df['APOE4'] = np.where(
aibl_demo_df['Demographic.ApoE genotype'].str.contains('E4', na=False),
    1,
    np.where(aibl_demo_df['Demographic.ApoE genotype'].isna(),np.nan,0)
)
omics_with_demo_df = pd.merge(merge_df, aibl_demo_df, on = ['AIBL.ID', 'Collection'], how='inner')
print(omics_with_demo_df.shape)

(90, 1945)
(90, 1958)

In [20]:
cols = omics_with_demo_df.columns

print([col for col in cols if 'FA' in col])

['FA hydroxy(7:0)', 'FA methyl(8:0)', 'FA oxo(9:0) oxo-nonanoic acid', 'FA hydroxy(9:0) hydroxy-nonanoic acid', 'FA (10:2) Decadienoic acid', 'FA methyl(7:0)', 'FA methyl(12:0) dodecanoic acid', 'FA hydroxy(12:0) dodecanoic acid', 'FA (14:1)nonanoic acid', 'FA (13:2) tridecadienoic acid', 'FA hydroxy(13:0) tridecanoic acid', 'FA oxo(14:1) cyclopentanebutanoic acid', 'FA oxo(14:2) cyclopentanebutanoic acid', 'FA methyl(14:0)', 'FA methyl(14:0) dodecanedioic acid', 'FA (16:3)', 'FA methyl(15:0) tridecanedioic acid', 'FA methyl(16:0)] tetradecanedioic acid', 'FA (18:4)', 'FA (18:3)', 'FA (18:2)', 'FA hydroxy(18:1)', 'FA (19:1)', 'FA hydroxy(18:0)', 'FA hydroxy(26:0)', 'FAHFA(16:0/9-O-18:0)', 'FABP4', 'FAM20C', 'FAP', 'HGFAC', 'IGFALS']

In [18]:
omics_with_demo_df.to_csv('../data/merged_data/omics_aibl_demo.csv',index=False)

In [19]:
missing_values = omics_with_demo_df.isnull().sum()
missing_info = {col: count for col, count in missing_values.items() if count > 0}
print(missing_info)

{'Demographic.ApoE genotype': 2, 'Demographic.Years of Education Exact': 6, 'Demographic.Primary Occupation': 2, 'Demographic.Retirement Status': 1, 'Demographic.Current Marital Status': 1, 'Demographic.Country of Birth': 1, 'Demographic.Handedness': 1, 'Vital Signs.Body Mass Index': 10, 'APOE4': 2}

In [ ]:
######## Go to R to impute

In [18]:
print(omics_with_demo_df.select_dtypes(include=['object', 'category']).columns)

Index(['Gender', 'label', 'Demographic.ApoE genotype',
       'Demographic.Years of Education', 'Demographic.Sex',
       'Demographic.Primary Occupation', 'Demographic.Retirement Status',
       'Demographic.Current Marital Status', 'Demographic.Country of Birth',
       'Demographic.Handedness'],
      dtype='object')

In [19]:
###### solve for missing

def impute_education(row):
    range_map = {
        '9-12': 10,
        '13-15': 14,
        '7-8': 7,
        '15+': 15
    }
    
    education_range = row['Demographic.Years of Education']
    if pd.isna(row['Demographic.Years of Education Exact']):
        return range_map[education_range]
    else:
        return row['Demographic.Years of Education Exact']

In [20]:
omics_with_demo_df_no_missing = omics_with_demo_df.copy()

omics_with_demo_df_no_missing['Demographic.Years of Education Exact'] = omics_with_demo_df_no_missing.apply(impute_education, axis=1)
omics_with_demo_df_no_missing['APOE4'] = omics_with_demo_df_no_missing['APOE4'].fillna(0)

omics_with_demo_df_no_missing = omics_with_demo_df_no_missing.drop(columns = ['Demographic.Years of Education','Demographic.ApoE genotype'])
print(omics_with_demo_df_no_missing.isna().sum().sum())
print(omics_with_demo_df_no_missing.shape)

16
(90, 1918)

In [21]:
print(omics_with_demo_df_no_missing.columns[omics_with_demo_df_no_missing.isnull().any()])

Index(['Demographic.Primary Occupation', 'Demographic.Retirement Status',
       'Demographic.Current Marital Status', 'Demographic.Country of Birth',
       'Demographic.Handedness', 'Vital Signs.Body Mass Index'],
      dtype='object')

In [22]:
omics_with_demo_df_no_missing.to_csv('../data/merged_data/omics_aibl_demo_no_missing.csv')

In [23]:
merge_df.to_csv('../data/merged_data/omics_merge.csv')

In [24]:
combined_features = [(name, 'proteomics') for name in proteomics_cols] + \
                    [(name, 'metabolomics') for name in metabolomics_cols] + \
                    [(name, 'demographic') for name in ['Demographic.Sex','APOE4','Age','Demographic.Years of Education Exact']]

features_df = pd.DataFrame(combined_features, columns=['feature', 'type'])

features_df.to_csv('../data/merged_data/feature_type.csv')

In [25]:
AIBL_raw = pd.read_excel('../data/raw_data/AIBL_2023.xlsx')
AIBL_raw['Demographic.YearMonthOfBirth']=AIBL_raw['Demographic.YearMonthOfBirth'].astype(str) + '01'
AIBL_raw['Demographic.YearMonthOfBirth'] = pd.to_datetime(AIBL_raw['Demographic.YearMonthOfBirth'], format='%Y%m%d')
AIBL_raw['Progress Summary.Date of NP assessment'] = pd.to_datetime(AIBL_raw['Progress Summary.Date of NP assessment'], format='%d/%m/%Y')
AIBL_raw['Age'] = (AIBL_raw['Progress Summary.Date of NP assessment'] - AIBL_raw['Demographic.YearMonthOfBirth']).dt.days // 365

KeyboardInterrupt:

In [ ]:
check = pd.read_excel('../data/raw_data/20230808 (AIBL) Liang ORCA Serum 500uL.xlsx', sheet_name='for python')
check

,Tube Pos.,Tube Barcode,Sample ID,Timepoint,Sample Type,Vol (µL),Comments,Site
0,A01,NUOM151985,812,C10,serum,500,NaN,Melb
1,A02,NUMJ558709,98,C10,serum,500,NaN,Melb
2,A03,NUOH688943,1705,C4,serum,500,NaN,Melb
3,A04,NUOL450223,907,C9,serum,500,NaN,Melb
4,A05,NUNS061588,1710,C5,serum,500,NaN,Melb
...,...,...,...,...,...,...,...,...
98,A03,NUGG198672,1311,C5,serum,500,NaN,Perth
99,A04,NUGF793072,527,C8,serum,500,NaN,Perth
100,A05,NUGF793559,528,C8,serum,500,NaN,Perth
101,A06,NUGF057235,316,C8,serum,500,NaN,Perth
102,A07,NUGF056759,317,C8,serum,500,NaN,Perth

In [ ]:
cols_saved=['AIBL ID', 'Collection', 'Age', 'Demographic.Sex', 'Enrolment', 'Recruitment', 'Image.PET.Centiloid', 'Image.PET.Amyloid.PIB.ScanDate', 'Image.PET.Amyloid.PIB.SUVR_CCM', 
            'Image.PET.Amyloid.Site', 'Image.PET.Amyloid.Tracer', 'Image.PET.Amyloid.Status', 'Image.PET.Amyloid.ScanDate', 'Progress Summary.Date of NP assessment', 'Neuropsych.Simple Classification']
AIBL_select = AIBL_raw.loc[:, cols_saved]
AIBL_select

,AIBL ID,Collection,Age,Demographic.Sex,Enrolment,Recruitment,Image.PET.Centiloid,Image.PET.Amyloid.PIB.ScanDate,Image.PET.Amyloid.PIB.SUVR_CCM,Image.PET.Amyloid.Site,Image.PET.Amyloid.Tracer,Image.PET.Amyloid.Status,Image.PET.Amyloid.ScanDate,Progress Summary.Date of NP assessment,Neuropsych.Simple Classification
0,2,1,65.0,Male,AIBL Inception Cohort,AIBL,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2006-11-03,HC
1,2,2,67.0,Male,AIBL Inception Cohort,AIBL,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2008-09-16,HC
2,2,3,68.0,Male,AIBL Inception Cohort,AIBL,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2010-03-24,HC
3,2,4,70.0,Male,AIBL Inception Cohort,AIBL,-13.8,NaN,NaN,Austin Hospital,FBP,Negative,15/11/2011,2011-09-16,HC
4,2,5,71.0,Male,AIBL Inception Cohort,AIBL,-15.6,NaN,NaN,Austin Hospital,FBP,Negative,21/05/2013,2013-04-11,HC
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
37813,3667,7,NaN,Male,Enrichment Round 1,ADNeT-TS-National,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaT,NaN
37814,3667,8,NaN,Male,Enrichment Round 1,ADNeT-TS-National,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaT,NaN
37815,3667,9,NaN,Male,Enrichment Round 1,ADNeT-TS-National,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaT,NaN
37816,3667,10,NaN,Male,Enrichment Round 1,ADNeT-TS-National,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaT,NaN
37817,3667,11,NaN,Male,Enrichment Round 1,ADNeT-TS-National,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaT,NaN

In [ ]:
sample_ids_to_remove = set(check['Sample ID'])
AIBL_filtered = AIBL_select[~AIBL_select['AIBL ID'].isin(sample_ids_to_remove)]
AIBL_filtered = AIBL_filtered.reset_index(drop=True)
AIBL_filtered

,AIBL ID,Collection,Age,Demographic.Sex,Enrolment,Recruitment,Image.PET.Centiloid,Image.PET.Amyloid.PIB.ScanDate,Image.PET.Amyloid.PIB.SUVR_CCM,Image.PET.Amyloid.Site,Image.PET.Amyloid.Tracer,Image.PET.Amyloid.Status,Image.PET.Amyloid.ScanDate,Progress Summary.Date of NP assessment,Neuropsych.Simple Classification
0,2,1,65.0,Male,AIBL Inception Cohort,AIBL,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2006-11-03,HC
1,2,2,67.0,Male,AIBL Inception Cohort,AIBL,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2008-09-16,HC
2,2,3,68.0,Male,AIBL Inception Cohort,AIBL,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2010-03-24,HC
3,2,4,70.0,Male,AIBL Inception Cohort,AIBL,-13.8,NaN,NaN,Austin Hospital,FBP,Negative,15/11/2011,2011-09-16,HC
4,2,5,71.0,Male,AIBL Inception Cohort,AIBL,-15.6,NaN,NaN,Austin Hospital,FBP,Negative,21/05/2013,2013-04-11,HC
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
36702,3667,7,NaN,Male,Enrichment Round 1,ADNeT-TS-National,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaT,NaN
36703,3667,8,NaN,Male,Enrichment Round 1,ADNeT-TS-National,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaT,NaN
36704,3667,9,NaN,Male,Enrichment Round 1,ADNeT-TS-National,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaT,NaN
36705,3667,10,NaN,Male,Enrichment Round 1,ADNeT-TS-National,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaT,NaN
36706,3667,11,NaN,Male,Enrichment Round 1,ADNeT-TS-National,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaT,NaN

In [ ]:
columns_to_check = ['Image.PET.Amyloid.Status', 'Image.PET.Centiloid', 'Image.PET.Amyloid.PIB.SUVR_CCM']
def all_empty(group):
    return group[columns_to_check].isna().all().all()
AIBL_filtered_withab = AIBL_filtered.groupby('AIBL ID').filter(lambda x: not all_empty(x))
AIBL_filtered_withab = AIBL_filtered_withab.reset_index(drop=True)
print(AIBL_filtered_withab['AIBL ID'].nunique())
AIBL_filtered_withab

1992

,AIBL ID,Collection,Age,Demographic.Sex,Enrolment,Recruitment,Image.PET.Centiloid,Image.PET.Amyloid.PIB.ScanDate,Image.PET.Amyloid.PIB.SUVR_CCM,Image.PET.Amyloid.Site,Image.PET.Amyloid.Tracer,Image.PET.Amyloid.Status,Image.PET.Amyloid.ScanDate,Progress Summary.Date of NP assessment,Neuropsych.Simple Classification
0,2,1,65.0,Male,AIBL Inception Cohort,AIBL,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2006-11-03,HC
1,2,2,67.0,Male,AIBL Inception Cohort,AIBL,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2008-09-16,HC
2,2,3,68.0,Male,AIBL Inception Cohort,AIBL,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2010-03-24,HC
3,2,4,70.0,Male,AIBL Inception Cohort,AIBL,-13.8,NaN,NaN,Austin Hospital,FBP,Negative,15/11/2011,2011-09-16,HC
4,2,5,71.0,Male,AIBL Inception Cohort,AIBL,-15.6,NaN,NaN,Austin Hospital,FBP,Negative,21/05/2013,2013-04-11,HC
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
21907,2999,7,NaN,Male,Enrichment Round 1,ADNeT-TS-National,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaT,NaN
21908,2999,8,NaN,Male,Enrichment Round 1,ADNeT-TS-National,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaT,NaN
21909,2999,9,NaN,Male,Enrichment Round 1,ADNeT-TS-National,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaT,NaN
21910,2999,10,NaN,Male,Enrichment Round 1,ADNeT-TS-National,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaT,NaN
21911,2999,11,NaN,Male,Enrichment Round 1,ADNeT-TS-National,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaT,NaN

In [ ]:
AIBL_filtered_withab_HN = AIBL_filtered_withab[AIBL_filtered_withab['Image.PET.Amyloid.Status'].isin(['Negative', 'High'])]
AIBL_filtered_withab_HN = AIBL_filtered_withab_HN.reset_index(drop=True)
AIBL_filtered_withab_HN

,AIBL ID,Collection,Age,Demographic.Sex,Enrolment,Recruitment,Image.PET.Centiloid,Image.PET.Amyloid.PIB.ScanDate,Image.PET.Amyloid.PIB.SUVR_CCM,Image.PET.Amyloid.Site,Image.PET.Amyloid.Tracer,Image.PET.Amyloid.Status,Image.PET.Amyloid.ScanDate,Progress Summary.Date of NP assessment,Neuropsych.Simple Classification
0,2,4,70.0,Male,AIBL Inception Cohort,AIBL,-13.8,NaN,NaN,Austin Hospital,FBP,Negative,15/11/2011,2011-09-16,HC
1,2,5,71.0,Male,AIBL Inception Cohort,AIBL,-15.6,NaN,NaN,Austin Hospital,FBP,Negative,21/05/2013,2013-04-11,HC
2,3,1,68.0,Female,AIBL Inception Cohort,AIBL,108.1,02/11/2007,2.50,Austin Hospital,PIB,High,02/11/2007,2007-10-12,HC
3,3,2,70.0,Female,AIBL Inception Cohort,AIBL,106.0,29/05/2009,2.46,Austin Hospital,PIB,High,29/05/2009,2009-05-29,HC
4,3,3,71.0,Female,AIBL Inception Cohort,AIBL,113.0,25/10/2010,2.57,Austin Hospital,PIB,High,25/10/2010,2010-10-25,HC
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3845,2987,1,82.0,Male,Enrichment Round 1,ADNeT-TS-National,128.2,NaN,NaN,Austin Hospital,NAV,High,19/05/2021,2021-06-11,NaN
3846,2989,1,66.0,Male,Enrichment Round 1,ADNeT-TS-National,84.0,NaN,NaN,Austin Hospital,NAV,High,11/05/2021,2021-07-02,NaN
3847,2992,1,73.0,Female,Enrichment Round 1,ADNeT-TS-National,-2.5,NaN,NaN,Austin Hospital,NAV,Negative,16/06/2021,2021-07-06,NaN
3848,2993,1,76.0,Male,Enrichment Round 1,ADNeT-TS-National,9.5,NaN,NaN,Austin Hospital,NAV,Negative,19/05/2021,2021-08-13,NaN
3849,2999,1,86.0,Male,Enrichment Round 1,ADNeT-TS-National,72.3,NaN,NaN,Austin Hospital,NAV,High,16/06/2021,2021-05-19,NaN

In [ ]:
# AIBL_filtered_withab_HN = AIBL_filtered_withab_HN[(~((AIBL_filtered_withab_HN['Image.PET.Amyloid.Status'] == 'High') & 
#                               (AIBL_filtered_withab_HN['Neuropsych.Simple Classification'] == 'AD'))) &
#                               (AIBL_filtered_withab_HN['Neuropsych.Simple Classification'].notna())]
AIBL_filtered_withab_HN = AIBL_filtered_withab_HN[AIBL_filtered_withab_HN['Neuropsych.Simple Classification']=="HC"]
AIBL_filtered_withab_HN

,AIBL ID,Collection,Age,Demographic.Sex,Enrolment,Recruitment,Image.PET.Centiloid,Image.PET.Amyloid.PIB.ScanDate,Image.PET.Amyloid.PIB.SUVR_CCM,Image.PET.Amyloid.Site,Image.PET.Amyloid.Tracer,Image.PET.Amyloid.Status,Image.PET.Amyloid.ScanDate,Progress Summary.Date of NP assessment,Neuropsych.Simple Classification
0,2,4,70.0,Male,AIBL Inception Cohort,AIBL,-13.8,NaN,NaN,Austin Hospital,FBP,Negative,15/11/2011,2011-09-16,HC
1,2,5,71.0,Male,AIBL Inception Cohort,AIBL,-15.6,NaN,NaN,Austin Hospital,FBP,Negative,21/05/2013,2013-04-11,HC
2,3,1,68.0,Female,AIBL Inception Cohort,AIBL,108.1,02/11/2007,2.50,Austin Hospital,PIB,High,02/11/2007,2007-10-12,HC
3,3,2,70.0,Female,AIBL Inception Cohort,AIBL,106.0,29/05/2009,2.46,Austin Hospital,PIB,High,29/05/2009,2009-05-29,HC
4,3,3,71.0,Female,AIBL Inception Cohort,AIBL,113.0,25/10/2010,2.57,Austin Hospital,PIB,High,25/10/2010,2010-10-25,HC
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3722,2792,1,72.0,Male,Enrichment Round 1,ADNET-TS-M,127.4,NaN,NaN,Brain Research Institute,NAV,High,19/12/2019,2020-01-21,HC
3745,2832,1,72.0,Male,Enrichment Round 1,ADNET-TS-M,-4.1,NaN,NaN,Austin Hospital,NAV,Negative,23/06/2020,2020-06-23,HC
3765,2863,1,78.0,Female,Enrichment Round 1,ADNET-TS-M,79.1,NaN,NaN,Austin Hospital,NAV,High,27/07/2020,2020-09-08,HC
3786,2893,1,55.0,Female,Enrichment Round 1,AIBL,-8.1,NaN,NaN,OM.PRC.Hollywood,NAV,Negative,17/12/2020,2020-11-30,HC
3807,2926,1,62.0,Male,Enrichment Round 1,AIBL,2.1,NaN,NaN,OM.PRC.Hollywood,NAV,Negative,17/12/2020,2020-11-27,HC

In [ ]:
AIBL_filtered_withab_HN=AIBL_filtered_withab_HN.dropna()
AIBL_filtered_withab_HN

,AIBL ID,Collection,Age,Demographic.Sex,Enrolment,Recruitment,Image.PET.Centiloid,Image.PET.Amyloid.PIB.ScanDate,Image.PET.Amyloid.PIB.SUVR_CCM,Image.PET.Amyloid.Site,Image.PET.Amyloid.Tracer,Image.PET.Amyloid.Status,Image.PET.Amyloid.ScanDate,Progress Summary.Date of NP assessment,Neuropsych.Simple Classification
2,3,1,68.0,Female,AIBL Inception Cohort,AIBL,108.1,02/11/2007,2.50,Austin Hospital,PIB,High,02/11/2007,2007-10-12,HC
3,3,2,70.0,Female,AIBL Inception Cohort,AIBL,106.0,29/05/2009,2.46,Austin Hospital,PIB,High,29/05/2009,2009-05-29,HC
4,3,3,71.0,Female,AIBL Inception Cohort,AIBL,113.0,25/10/2010,2.57,Austin Hospital,PIB,High,25/10/2010,2010-10-25,HC
8,4,1,84.0,Female,AIBL Inception Cohort,AIBL,50.7,23/03/2007,1.82,Austin Hospital,PIB,High,23/03/2007,2007-02-02,HC
9,4,2,86.0,Female,AIBL Inception Cohort,AIBL,64.5,17/10/2008,1.97,Austin Hospital,PIB,High,17/10/2008,2008-08-04,HC
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3575,2571,1,79.0,Male,Enrichment Round 1,AIBL,10.6,06/07/2018,1.35,OM.PRC.Hollywood,PIB,Negative,06/07/2018,2018-06-25,HC
3576,2572,1,77.0,Female,Enrichment Round 1,AIBL,10.9,06/07/2018,1.31,OM.PRC.Hollywood,PIB,Negative,06/07/2018,2018-06-25,HC
3578,2574,1,75.0,Male,Enrichment Round 1,AIBL,100.1,16/08/2018,2.44,OM.PRC.Hollywood,PIB,High,16/08/2018,2018-07-03,HC
3584,2579,1,62.0,Female,Enrichment Round 1,AIBL,35.3,20/07/2018,1.62,OM.PRC.Hollywood,PIB,High,20/07/2018,2018-07-16,HC
3588,2584,1,77.0,Female,Enrichment Round 1,AIBL,90.9,04/01/2018,2.40,SCGH,PIB,High,04/01/2018,2018-08-10,HC

In [ ]:
print(AIBL_filtered_withab_HN['AIBL ID'].nunique())

360

In [37]:
columns_to_export = ['AIBL ID', 'Collection', 'Age', 'Demographic.Sex', 'Image.PET.Centiloid', 'Image.PET.Amyloid.PIB.SUVR_CCM']
negative_amyloid_subset = AIBL_filtered_withab_HN.loc[
    AIBL_filtered_withab_HN['Image.PET.Amyloid.Status'] == 'Negative',
    columns_to_export
]

print(negative_amyloid_subset['AIBL ID'].nunique())
negative_amyloid_subset

248

,AIBL ID,Collection,Age,Demographic.Sex,Image.PET.Centiloid,Image.PET.Amyloid.PIB.SUVR_CCM
13,5,2,74.0,Male,3.7,1.25
14,5,3,76.0,Male,-0.3,1.20
15,5,4,77.0,Male,6.0,1.27
44,18,2,65.0,Male,-6.9,1.15
45,18,3,67.0,Male,-6.1,1.15
...,...,...,...,...,...,...
3567,2565,1,68.0,Male,1.7,1.23
3570,2567,1,71.0,Male,-3.5,1.15
3571,2568,1,76.0,Male,3.8,1.30
3575,2571,1,79.0,Male,10.6,1.35
3576,2572,1,77.0,Female,10.9,1.31

In [38]:
high_amyloid_subset = AIBL_filtered_withab_HN.loc[
    AIBL_filtered_withab_HN['Image.PET.Amyloid.Status'] == 'High',
    columns_to_export
]

print(high_amyloid_subset['AIBL ID'].nunique())
high_amyloid_subset

119

,AIBL ID,Collection,Age,Demographic.Sex,Image.PET.Centiloid,Image.PET.Amyloid.PIB.SUVR_CCM
2,3,1,68.0,Female,108.1,2.50
3,3,2,70.0,Female,106.0,2.46
4,3,3,71.0,Female,113.0,2.57
8,4,1,84.0,Female,50.7,1.82
9,4,2,86.0,Female,64.5,1.97
...,...,...,...,...,...,...
3497,2507,1,83.0,Male,28.9,1.59
3533,2536,1,76.0,Male,81.5,2.23
3578,2574,1,75.0,Male,100.1,2.44
3584,2579,1,62.0,Female,35.3,1.62
3588,2584,1,77.0,Female,90.9,2.40

In [39]:
excel_file = 'check_new_validation.xlsx'
with pd.ExcelWriter(excel_file, engine='openpyxl') as writer:
    # Write each dataframe to a different worksheet
    negative_amyloid_subset.to_excel(writer, sheet_name='Amyloid-beta Negative', index=False)
    high_amyloid_subset.to_excel(writer, sheet_name='Amyloid-beta High', index=False)
    AIBL_filtered_withab_HN.to_excel(writer, sheet_name='Full', index=False)